server:
  port: 8081
  servlet:
    context-path: /sso-client-a

# sso　认证配置
oauth2-server: http://localhost:80/auth-server

security:
  oauth2:
    client:
      client-id: sso-client-a
      client-secret: test
      access-token-uri: ${oauth2-server}/oauth/token
      user-authorization-uri: ${oauth2-server}/oauth/authorize
      registered-redirect-uri:
        - "http://localhost:8081/sso-client-a"
    resource:
      jwt:
        key-uri: ${oauth2-server}/oauth/token_key
        key-value: RSA-key

spring:
  thymeleaf:
    cache: false